/* cSpell:disable */
export const mockVideosList = {
  kind: 'youtube#videoListResponse',
  etag: 'l4-oBqhLZ8I86jugUT3voynrxo8',
  items: [
    {
      kind: 'youtube#video',
      etag: 'AsBYU2YmvEkhPX6ot-9ROOa6inE',
      id: '25CbZLtF0K4',
      contentDetails: {
        duration: 'PT8M29S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '61594',
        likeCount: '545',
        favoriteCount: '0',
        commentCount: '33',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'HMc2BCFUtl9GZc_MlzD6gtB7wEc',
      id: 'hY7m5jjJ9mM',
      contentDetails: {
        duration: 'PT10M2S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '115035908',
        likeCount: '506130',
        favoriteCount: '0',
        commentCount: '51195',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'fTn6Fxgp2S7bIKqYjfkVjazQBX4',
      id: 'xJrwYU3vyKw',
      contentDetails: {
        duration: 'PT10M55S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '96192',
        likeCount: '1069',
        favoriteCount: '0',
        commentCount: '76',
      },
    },
    {
      kind: 'youtube#video',
      etag: '-Bw1HuyKIeMv_0de3itzSam061c',
      id: 'DXUAyRRkI6k',
      contentDetails: {
        duration: 'PT4M23S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '421620736',
        likeCount: '1687549',
        favoriteCount: '0',
        commentCount: '3986',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'yFwmdBwYx49RuP0ztz0kBy9cTcg',
      id: '4gFpeDkQDNU',
      contentDetails: {
        duration: 'PT10M16S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '181357',
        likeCount: '1736',
        favoriteCount: '0',
        commentCount: '144',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'nmBouWyLkp6nQqV1q_F9pIKnp9A',
      id: 'eX2qFMC8cFo',
      contentDetails: {
        duration: 'PT9M10S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '56546257',
        likeCount: '859550',
        favoriteCount: '0',
        commentCount: '23769',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'Vj7lQcL9UHSQs0gGOabMayuYCO8',
      id: 'zHzUcE2mi9I',
      contentDetails: {
        duration: 'PT8M47S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '123782',
        likeCount: '2246',
        favoriteCount: '0',
        commentCount: '73',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'TGqBveU-81rlKZVUF9y8h1SAT3I',
      id: 'cii24uI6M10',
      contentDetails: {
        duration: 'PT9M46S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '50504',
        likeCount: '903',
        favoriteCount: '0',
        commentCount: '47',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'fB5MnHiVHLs2KGOSZB_fZaVlr5s',
      id: 'm4Ew-2x8hOc',
      contentDetails: {
        duration: 'PT27M3S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '2429',
        likeCount: '28',
        favoriteCount: '0',
        commentCount: '1',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'tWYkv_LXZGGAnYKanUye7pzb19w',
      id: '35lcsFGu_I0',
      contentDetails: {
        duration: 'PT10M46S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '9244237',
        likeCount: '182354',
        favoriteCount: '0',
        commentCount: '10293',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'rKBSDUk9ZCYaTuEc-iEbaTuisO8',
      id: 'xbs7FT7dXYc',
      contentDetails: {
        duration: 'PT8H5M42S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '22764253',
        likeCount: '80489',
        favoriteCount: '0',
        commentCount: '3584',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'VLsHiBmM8LAnWYWTaEafF26hVr4',
      id: 'HuibFNsYT9o',
      contentDetails: {
        duration: 'PT10M32S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '130311',
        likeCount: '1056',
        favoriteCount: '0',
        commentCount: '42',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'eQGq3Nf9xd6x44wjJst_Fv85mnw',
      id: 'BwSQyuUxYfI',
      contentDetails: {
        duration: 'PT5M44S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '26849345',
        likeCount: '131190',
        favoriteCount: '0',
        commentCount: '4755',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'knn2RX4wC5Xi6epvZ7m8jlT44HI',
      id: 'UkozMHMRLM0',
      contentDetails: {
        duration: 'PT8M20S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '128790',
        likeCount: '2292',
        favoriteCount: '0',
        commentCount: '77',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'gfKMDsJe-HcLpl7VtfZmSpmuNSU',
      id: '7Is9rZLkcNs',
      contentDetails: {
        duration: 'PT10M54S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '267252',
        likeCount: '2974',
        favoriteCount: '0',
        commentCount: '220',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'GAj08SLuKpGjOSNiOfN7MD-DmhY',
      id: 'Zfi9rBDW3s8',
      contentDetails: {
        duration: 'PT6M55S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        regionRestriction: {
          blocked: ['CU', 'KP', 'SY'],
        },
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '948729',
        likeCount: '9431',
        favoriteCount: '0',
        commentCount: '847',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'xdIOGqKHaDzNvjhdizqp9EnuhQg',
      id: 'RHMckJ7jMNQ',
      contentDetails: {
        duration: 'PT8M10S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '33036',
        likeCount: '477',
        favoriteCount: '0',
        commentCount: '31',
      },
    },
    {
      kind: 'youtube#video',
      etag: '2UJph2UB9_OU4y_My8F5Ls0T6Ro',
      id: '8gd_ohoPzYc',
      contentDetails: {
        duration: 'PT4M36S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '10412059',
        likeCount: '120066',
        favoriteCount: '0',
        commentCount: '5901',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'Mi00XqSUPXaHdj5eeZYlTFR58Lc',
      id: 'Z5-ra2Hq5OU',
      contentDetails: {
        duration: 'PT10M36S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '842005',
        likeCount: '6355',
        favoriteCount: '0',
        commentCount: '231',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'kcc_-oczg90A5krKa_Y8E96rdBg',
      id: 'kO-wM8lPeDQ',
      contentDetails: {
        duration: 'PT7M16S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '23384',
        likeCount: '303',
        favoriteCount: '0',
        commentCount: '15',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'F4kvLrwYgBTd6_zb4XhY9b1ec84',
      id: 'GOj0jroeVJc',
      contentDetails: {
        duration: 'PT8M25S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '33338',
        likeCount: '402',
        favoriteCount: '0',
        commentCount: '24',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'k65HcTb31bw6Xbv4Ug73-h8VEfs',
      id: 'FTIM-797FJw',
      contentDetails: {
        duration: 'PT3M17S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '81559',
        likeCount: '5480',
        favoriteCount: '0',
        commentCount: '410',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'x26Q6O2KHM8yg1Hws8zPeuXYDhI',
      id: 'WXrjzGZXmqI',
      contentDetails: {
        duration: 'PT8M4S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '20725',
        likeCount: '302',
        favoriteCount: '0',
        commentCount: '23',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'fmYK5eiWbo0rlZYoZf__u23tPp4',
      id: 'aBzTVWQDx9I',
      contentDetails: {
        duration: 'PT8M3S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '30998',
        likeCount: '353',
        favoriteCount: '0',
        commentCount: '39',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'JB82zErc2ArGCUfsVlrIkD1jeqE',
      id: '-CygdOAdpFw',
      contentDetails: {
        duration: 'PT9M37S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: false,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '123502',
        likeCount: '1572',
        favoriteCount: '0',
        commentCount: '87',
      },
    },
  ],
  pageInfo: {
    totalResults: 25,
    resultsPerPage: 25,
  },
};
